#!/usr/bin/env python3
"""build_fixtures.py — generate 5 demo PDF fixtures for pdf-evidence v0.1.

PATCH 2 — minimum 5 fixture cases. Each fixture is a directory under
scaffolding/fixtures/NN_<name>/ containing:
  - source.pdf (or source_a.pdf + source_b.pdf for multi-pdf)
  - case.json (input + expected ground-truth)

The PDFs are generated by reportlab (no copyrighted content). They are
deliberately simple text PDFs so that pdfplumber can parse them reliably
and the eval loop can run end-to-end without OCR.

Usage:
    python build_fixtures.py            # build all 5
    python build_fixtures.py --check    # verify reportlab available + show plan

After building, the eval loop is run by placing a skill_output.json next to
each case.json (the skill's actual output) and running eval_runner.py.
For v0.1 demo purposes, build_fixtures.py ALSO writes a baseline
skill_output.json for each case so the loop has something to evaluate.
These baseline outputs are realistic but should be regenerated by running
the actual pdf-evidence skill on each fixture.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

FIXTURES_DIR = Path(__file__).resolve().parent

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    )
    from reportlab.lib import colors
except ImportError:
    print("ERROR: reportlab not installed. Run: pip install reportlab", file=sys.stderr)
    sys.exit(2)


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle(name="Body", parent=ss["Normal"], fontSize=11, leading=15, spaceAfter=6))
    ss.add(ParagraphStyle(name="H2", parent=ss["Heading2"], fontSize=13, spaceBefore=10, spaceAfter=6))
    return ss


def _save(path: Path, story):
    doc = SimpleDocTemplate(str(path), pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    doc.build(story)


# ---------------------------------------------------------------------------
# Fixture 01 — text_qa
# ---------------------------------------------------------------------------

def build_01_text_qa():
    d = FIXTURES_DIR / "01_text_qa"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    story = [
        Paragraph("Báo cáo Tài chính Quý 1 năm 2026", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Công ty ABC (demo)", ss["Body"]),
        PageBreak(),
        Paragraph("Tổng quan tài chính", ss["H2"]),
        Paragraph(
            "Trong quý 1 năm 2026, công ty ABC ghi nhận doanh thu hợp nhất đạt "
            "<b>12.500 tỷ đồng</b>, tăng 11% so với cùng kỳ năm 2025. "
            "Biên lợi nhuận gộp đạt 24%, cao hơn 2 phần trăm so với mức 22% của quý 1 năm 2025.",
            ss["Body"],
        ),
        Paragraph(
            "Lợi nhuận sau thuế đạt 1.800 tỷ đồng. Tổng tài sản cuối kỳ đạt 45.000 tỷ đồng.",
            ss["Body"],
        ),
    ]
    _save(d / "source.pdf", story)

    case = {
        "id": "01_text_qa",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Doanh thu Q1/2026 của công ty ABC là bao nhiêu?",
        "task": "qa",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["12.500", "tỷ"],
            "answer_not_contains": ["15.000"],
            "abstention_expected": False,
            "expected_citations": [{"page": 2, "section_keyword": "Tổng quan"}],
            "expected_numbers": ["12.500"],
            "expected_clauses": [],
            "required_points": 1,
            "answered_points": 1,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")

    # Baseline skill output (realistic; should be regenerated by the actual skill)
    baseline = {
        "answer": "Doanh thu Q1/2026 của công ty ABC là 12.500 tỷ đồng [abc_2026, p.2, 'Tổng quan tài chính', 'doanh thu hợp nhất đạt 12.500 tỷ đồng, tăng 11%'].",
        "citations": [
            {"file": "abc_2026", "page": 2, "section": "Tổng quan tài chính",
             "quote": "doanh thu hợp nhất đạt 12.500 tỷ đồng", "note": None}
        ],
        "evidence": [{"page": 2, "snippet": "doanh thu hợp nhất đạt 12.500 tỷ đồng, tăng 11%"}],
        "confidence": 0.95,
        "abstention_flag": False,
        "abstention_reason": None,
        "outside_knowledge_used": False,
        "warnings": [],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 01_text_qa")


# ---------------------------------------------------------------------------
# Fixture 02 — no_answer_abstention
# ---------------------------------------------------------------------------

def build_02_no_answer_abstention():
    d = FIXTURES_DIR / "02_no_answer_abstention"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    story = [
        Paragraph("Báo cáo Tài chính Quý 1 năm 2026", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Tổng quan tài chính", ss["H2"]),
        Paragraph(
            "Doanh thu Q1/2026 đạt 12.500 tỷ đồng. Lợi nhuận sau thuế 1.800 tỷ đồng. "
            "Tổng tài sản 45.000 tỷ đồng.",
            ss["Body"],
        ),
    ]
    _save(d / "source.pdf", story)

    case = {
        "id": "02_no_answer_abstention",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Công ty ABC có bao nhiêu nhân viên tính đến cuối Q1/2026?",
        "task": "qa",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": [],
            "answer_not_contains": ["5.000", "10.000"],
            "abstention_expected": True,
            "expected_citations": [],
            "expected_numbers": [],
            "expected_clauses": [],
            "required_points": 1,
            "answered_points": 0,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")

    baseline = {
        "answer": "Insufficient evidence in the provided documents.",
        "citations": [],
        "evidence": [{"page": 1, "snippet": "Doanh thu Q1/2026 đạt 12.500 tỷ đồng."}],
        "confidence": 0.95,
        "abstention_flag": True,
        "abstention_reason": "Tài liệu chỉ đề cập doanh thu/lợi nhuận/tổng tài sản; không có thông tin nhân sự.",
        "outside_knowledge_used": False,
        "warnings": [],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 02_no_answer_abstention")


# ---------------------------------------------------------------------------
# Fixture 03 — table
# ---------------------------------------------------------------------------

def build_03_table():
    d = FIXTURES_DIR / "03_table"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    table_data = [
        ["Chỉ tiêu", "Q1/2026 (tỷ VNĐ)", "Q1/2025 (tỷ VNĐ)"],
        ["Doanh thu", "12.500", "11.250"],
        ["Lợi nhuận gộp", "3.000", "2.475"],
        ["Lợi nhuận sau thuế", "1.800", "1.500"],
    ]
    tbl = Table(table_data, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    story = [
        Paragraph("Báo cáo Tài chính Quý 1 năm 2026", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Bảng tổng hợp (đơn vị: tỷ VNĐ)", ss["H2"]),
        tbl,
        Spacer(1, 0.3 * cm),
        Paragraph("Nguồn: BCTC hợp nhất Q1/2026.", ss["Body"]),
    ]
    _save(d / "source.pdf", story)

    case = {
        "id": "03_table",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Doanh thu và lợi nhuận sau thuế Q1/2026 và Q1/2025 từ bảng tổng hợp?",
        "task": "extract_table",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["12.500", "1.800"],
            "answer_not_contains": [],
            "abstention_expected": False,
            "expected_citations": [{"page": 1, "section_keyword": "Bảng tổng hợp"}],
            "expected_numbers": ["12.500", "11.250", "1.800", "1.500"],
            "expected_clauses": [],
            "expected_table": {
                "headers": ["Chỉ tiêu", "Q1/2026 (tỷ VNĐ)", "Q1/2025 (tỷ VNĐ)"],
                "rows": [
                    ["Doanh thu", "12.500", "11.250"],
                    ["Lợi nhuận gộp", "3.000", "2.475"],
                    ["Lợi nhuận sau thuế", "1.800", "1.500"],
                ],
            },
            "required_points": 1,
            "answered_points": 1,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")

    baseline = {
        "answer": "Doanh thu Q1/2026: 12.500 tỷ; Q1/2025: 11.250 tỷ. LNST Q1/2026: 1.800 tỷ; Q1/2025: 1.500 tỷ [abc_2026, p.1, 'Bảng tổng hợp', bảng 1].",
        "citations": [
            {"file": "abc_2026", "page": 1, "section": "Bảng tổng hợp",
             "quote": "Bảng tổng hợp (đơn vị: tỷ VNĐ)", "note": None}
        ],
        "evidence": [{"page": 1, "snippet": "Doanh thu 12.500 / 11.250; LNST 1.800 / 1.500"}],
        "confidence": 0.85,
        "abstention_flag": False,
        "abstention_reason": None,
        "outside_knowledge_used": False,
        "warnings": ["Bảng parse có thể mất dấu hiệu merged cell — verify thủ công."],
        "expected_table": {
            "headers": ["Chỉ tiêu", "Q1/2026 (tỷ VNĐ)", "Q1/2025 (tỷ VNĐ)"],
            "rows": [
                ["Doanh thu", "12.500", "11.250"],
                ["Lợi nhuận gộp", "3.000", "2.475"],
                ["Lợi nhuận sau thuế", "1.800", "1.500"],
            ],
        },
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 03_table")


# ---------------------------------------------------------------------------
# Fixture 04 — legal_mock
# ---------------------------------------------------------------------------

def build_04_legal_mock():
    d = FIXTURES_DIR / "04_legal_mock"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    story = [
        Paragraph("Thông tư số 99/2026/TT-BTC (demo)", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph(
            "BAN HÀNH ngày 01/04/2026. CÓ HIỆU LỰC từ ngày 15/05/2026. "
            "ÁP DỤNG cho kỳ kế toán bắt đầu từ năm 2026.",
            ss["Body"],
        ),
        Spacer(1, 0.3 * cm),
        Paragraph("Điều 1. Phạm vi điều chỉnh", ss["H2"]),
        Paragraph(
            "Thông tư này quy định về chuẩn mực kế toán áp dụng cho doanh nghiệp "
            "niêm yết trên thị trường chứng khoán.",
            ss["Body"],
        ),
        Paragraph("Điều 2. Đối tượng áp dụng", ss["H2"]),
        Paragraph(
            "Khoản 1. Thông tư này áp dụng cho mọi doanh nghiệp niêm yết. "
            "Khoản 2. Doanh nghiệp chưa niêm yết có thể áp dụng tự nguyện.",
            ss["Body"],
        ),
    ]
    _save(d / "source.pdf", story)

    case = {
        "id": "04_legal_mock",
        "documents": [{"path": "source.pdf", "alias": "tt99_2026"}],
        "question": "Thông tư 99/2026 có hiệu lực từ khi nào, và Khoản 2 Điều 2 quy định điều gì?",
        "task": "qa",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["15/05/2026"],
            "answer_not_contains": ["01/04/2026 áp dụng"],
            "abstention_expected": False,
            "expected_citations": [{"page": 1, "section_keyword": "Điều 2"}],
            "expected_numbers": [],
            "expected_clauses": ["Điều 2", "Khoản 2"],
            "required_points": 2,
            "answered_points": 2,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")

    baseline = {
        "answer": "Thông tư 99/2026 có hiệu lực từ ngày 15/05/2026 [tt99_2026, p.1, 'Hiệu lực', 'CÓ HIỆU LỰC từ ngày 15/05/2026']. Khoản 2 Điều 2 quy định doanh nghiệp chưa niêm yết có thể áp dụng tự nguyện [tt99_2026, p.1, 'Điều 2', 'Khoản 2. Doanh nghiệp chưa niêm yết có thể áp dụng tự nguyện'].",
        "citations": [
            {"file": "tt99_2026", "page": 1, "section": "Hiệu lực",
             "quote": "CÓ HIỆU LỰC từ ngày 15/05/2026", "note": None},
            {"file": "tt99_2026", "page": 1, "section": "Điều 2",
             "quote": "Khoản 2. Doanh nghiệp chưa niêm yết có thể áp dụng tự nguyện", "note": None},
        ],
        "evidence": [
            {"page": 1, "snippet": "CÓ HIỆU LỰC từ ngày 15/05/2026"},
            {"page": 1, "snippet": "Khoản 2. Doanh nghiệp chưa niêm yết có thể áp dụng tự nguyện"},
        ],
        "confidence": 0.9,
        "abstention_flag": False,
        "abstention_reason": None,
        "outside_knowledge_used": False,
        "warnings": [],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 04_legal_mock")


# ---------------------------------------------------------------------------
# Fixture 05 — multipdf_comparison
# ---------------------------------------------------------------------------

def build_05_multipdf_comparison():
    d = FIXTURES_DIR / "05_multipdf_comparison"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()

    # source_a.pdf — original
    story_a = [
        Paragraph("Hợp đồng dịch vụ (bản gốc, demo)", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Điều 3. Giá trị hợp đồng", ss["H2"]),
        Paragraph("Khoản 1. Tổng giá trị hợp đồng là 10.000.000.000 đồng (mười tỷ đồng).", ss["Body"]),
        Paragraph("Điều 4. Thời hạn", ss["H2"]),
        Paragraph("Khoản 1. Hợp đồng có hiệu lực 12 tháng kể từ ngày ký.", ss["Body"]),
    ]
    _save(d / "source_a.pdf", story_a)

    # source_b.pdf — amendment
    story_b = [
        Paragraph("Phụ lục hợp đồng số 01 (demo)", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Phụ lục này sửa đổi, bổ sung Hợp đồng dịch vụ (bản gốc).", ss["Body"]),
        Paragraph("Điều 3. Giá trị hợp đồng (sửa đổi)", ss["H2"]),
        Paragraph(
            "Khoản 1. Tổng giá trị hợp đồng được điều chỉnh thành <b>12.000.000.000 đồng</b> "
            "(mười hai tỷ đồng). Bãi bỏ Khoản 1 Điều 3 của hợp đồng gốc.",
            ss["Body"],
        ),
        Paragraph("Điều 4. Thời hạn (giữ nguyên)", ss["H2"]),
        Paragraph("Không thay đổi.", ss["Body"]),
    ]
    _save(d / "source_b.pdf", story_b)

    case = {
        "id": "05_multipdf_comparison",
        "documents": [
            {"path": "source_a.pdf", "alias": "hop_dong_goc"},
            {"path": "source_b.pdf", "alias": "phu_luc_01"},
        ],
        "question": "Phụ lục 01 đã thay đổi điều gì so với hợp đồng gốc?",
        "task": "detect_changes",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["12.000.000.000", "10.000.000.000"],
            "answer_not_contains": [],
            "abstention_expected": False,
            "expected_citations": [
                {"page": 1, "section_keyword": "Điều 3"},
            ],
            "expected_numbers": ["10.000.000.000", "12.000.000.000"],
            "expected_clauses": ["Điều 3", "Khoản 1"],
            "required_points": 1,
            "answered_points": 1,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")

    baseline = {
        "answer": (
            "Phụ lục 01 thay đổi Điều 3: tổng giá trị hợp đồng tăng từ 10.000.000.000 đồng "
            "[hop_dong_goc, p.1, 'Điều 3', 'Tổng giá trị hợp đồng là 10.000.000.000 đồng'] "
            "lên 12.000.000.000 đồng [phu_luc_01, p.1, 'Điều 3', 'Tổng giá trị hợp đồng được điều chỉnh thành 12.000.000.000 đồng']. "
            "Điều 4 (thời hạn) không thay đổi [phu_luc_01, p.1, 'Điều 4', 'Không thay đổi']."
        ),
        "citations": [
            {"file": "hop_dong_goc", "page": 1, "section": "Điều 3",
             "quote": "Tổng giá trị hợp đồng là 10.000.000.000 đồng", "note": None},
            {"file": "phu_luc_01", "page": 1, "section": "Điều 3",
             "quote": "Tổng giá trị hợp đồng được điều chỉnh thành 12.000.000.000 đồng", "note": None},
            {"file": "phu_luc_01", "page": 1, "section": "Điều 4",
             "quote": "Không thay đổi", "note": None},
        ],
        "evidence": [
            {"page": 1, "snippet": "Tổng giá trị hợp đồng là 10.000.000.000 đồng"},
            {"page": 1, "snippet": "Tổng giá trị hợp đồng được điều chỉnh thành 12.000.000.000 đồng"},
            {"page": 1, "snippet": "Không thay đổi"},
        ],
        "confidence": 0.85,
        "abstention_flag": False,
        "abstention_reason": None,
        "outside_knowledge_used": False,
        "warnings": [],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 05_multipdf_comparison")


# ---------------------------------------------------------------------------
# v0.2.0 fixtures (P2.05) — groups A (partial abstention) + B (table wiring)
# ---------------------------------------------------------------------------

def build_06_partial_abstention_multi_part():
    """A.1 — multi-part question: revenue IS in PDF, headcount is NOT."""
    d = FIXTURES_DIR / "06_partial_abstention_multi_part"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    story = [
        Paragraph("Báo cáo Tài chính Quý 1 năm 2026", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Tổng quan tài chính", ss["H2"]),
        Paragraph(
            "Doanh thu hợp nhất Q1/2026 đạt 12.500 tỷ đồng. Lợi nhuận sau thuế 1.800 tỷ đồng. "
            "Tổng tài sản 45.000 tỷ đồng.",
            ss["Body"],
        ),
    ]
    _save(d / "source.pdf", story)
    case = {
        "id": "06_partial_abstention_multi_part",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Doanh thu Q1/2026 bao nhiêu, và công ty có bao nhiêu nhân viên?",
        "task": "qa",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["12.500"],
            "answer_not_contains": ["5.000", "10.000"],
            "abstention_expected": False,
            "partial_abstention_expected": True,
            "partial_abstention_topic": "nhân viên",
            "expected_citations": [{"page": 1, "section_keyword": "Tổng quan"}],
            "expected_numbers": ["12.500"],
            "required_points": 2,
            "answered_points": 1,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")
    baseline = {
        "answer": "Doanh thu Q1/2026 là 12.500 tỷ đồng [abc_2026, p.1, 'Tổng quan tài chính', 'doanh thu hợp nhất Q1/2026 đạt 12.500 tỷ đồng'].",
        "citations": [
            {"file": "abc_2026", "page": 1, "section": "Tổng quan tài chính",
             "quote": "doanh thu hợp nhất Q1/2026 đạt 12.500 tỷ đồng", "note": None}
        ],
        "evidence": [{"page": 1, "snippet": "doanh thu hợp nhất Q1/2026 đạt 12.500 tỷ đồng"}],
        "confidence": 0.9,
        "abstention_flag": False,
        "abstention_reason": None,
        "partial_abstentions": [
            {"claim_or_question_part": "số lượng nhân viên của công ty",
             "status": "not_enough_evidence",
             "reason": "Tài liệu chỉ đề cập doanh thu/lợi nhuận/tổng tài sản (p.1), không có thông tin nhân sự.",
             "missing_evidence": "employee count / headcount for 2026",
             "suggested_next_document": "Báo cáo thường niên — phần 'Đội ngũ nhân sự' hoặc phụ lục ESG.",
             "confidence": 0.95}
        ],
        "outside_knowledge_used": False,
        "warnings": [],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 06_partial_abstention_multi_part")


def build_07_conclusion_beyond_evidence():
    """A.2 — question asks for forecast/conclusion; PDF only has actuals."""
    d = FIXTURES_DIR / "07_conclusion_beyond_evidence"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    story = [
        Paragraph("Báo cáo Tài chính 2026", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Kết quả kinh doanh", ss["H2"]),
        Paragraph(
            "Năm 2026, công ty ABC đạt doanh thu 50.000 tỷ đồng. Lợi nhuận sau thuế 7.500 tỷ đồng. "
            "Đây là số liệu đã ghi nhận thực tế.",
            ss["Body"],
        ),
    ]
    _save(d / "source.pdf", story)
    case = {
        "id": "07_conclusion_beyond_evidence",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Dự báo doanh thu năm 2027 của công ty là bao nhiêu?",
        "task": "qa",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": [],
            "answer_not_contains": ["60.000", "55.000"],
            "abstention_expected": True,
            "partial_abstention_expected": False,
            "expected_citations": [],
            "expected_numbers": [],
            "required_points": 1,
            "answered_points": 0,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")
    baseline = {
        "answer": "Insufficient evidence in the provided documents.",
        "citations": [],
        "evidence": [{"page": 1, "snippet": "Năm 2026, công ty ABC đạt doanh thu 50.000 tỷ đồng."}],
        "confidence": 0.95,
        "abstention_flag": True,
        "abstention_reason": "Tài liệu chỉ có số liệu thực tế 2026, không có dự báo 2027.",
        "partial_abstentions": [],
        "outside_knowledge_used": False,
        "warnings": [],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 07_conclusion_beyond_evidence")


def build_08_legal_compare_missing_doc():
    """A.3 — compare task; only original provided, amendment missing."""
    d = FIXTURES_DIR / "08_legal_compare_missing_doc"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    story = [
        Paragraph("Hợp đồng dịch vụ (bản gốc)", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Điều 3. Giá trị hợp đồng", ss["H2"]),
        Paragraph("Khoản 1. Tổng giá trị hợp đồng là 10.000.000.000 đồng.", ss["Body"]),
    ]
    _save(d / "source.pdf", story)
    case = {
        "id": "08_legal_compare_missing_doc",
        "documents": [{"path": "source.pdf", "alias": "hop_dong_goc"}],
        "question": "Phụ lục 01 đã thay đổi Điều 3 thế nào so với hợp đồng gốc?",
        "task": "detect_changes",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": [],
            "answer_not_contains": ["12.000.000.000"],
            "abstention_expected": False,
            "partial_abstention_expected": True,
            "partial_abstention_topic": "Phụ lục 01",
            "expected_citations": [],
            "expected_numbers": [],
            "expected_clauses": ["Điều 3"],
            "required_points": 1,
            "answered_points": 0,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")
    baseline = {
        "answer": "Insufficient evidence to compare — Phụ lục 01 không được cung cấp.",
        "citations": [],
        "evidence": [{"page": 1, "snippet": "Tổng giá trị hợp đồng là 10.000.000.000 đồng"}],
        "confidence": 0.9,
        "abstention_flag": False,
        "abstention_reason": None,
        "partial_abstentions": [
            {"claim_or_question_part": "thay đổi Điều 3 trong Phụ lục 01",
             "status": "not_enough_evidence",
             "reason": "Chỉ có hợp đồng gốc (10.000.000.000 đồng ở Điều 3). Phụ lục 01 không được cung cấp.",
             "missing_evidence": "Phụ lục 01 / văn bản sửa đổi",
             "suggested_next_document": "Cung cấp Phụ lục 01 để so sánh.",
             "confidence": 0.95}
        ],
        "outside_knowledge_used": False,
        "warnings": [],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 08_legal_compare_missing_doc")


def build_09_financial_missing_period():
    """A.4 — financial question about Q3; PDF only has Q1/Q2."""
    d = FIXTURES_DIR / "09_financial_missing_period"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    table_data = [
        ["Chỉ tiêu", "Q1/2026 (tỷ VNĐ)", "Q2/2026 (tỷ VNĐ)"],
        ["Doanh thu", "12.500", "13.200"],
    ]
    tbl = Table(table_data, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    story = [
        Paragraph("Báo cáo Tài chính nửa đầu 2026", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Bảng doanh thu (đơn vị: tỷ VNĐ)", ss["H2"]),
        tbl,
    ]
    _save(d / "source.pdf", story)
    case = {
        "id": "09_financial_missing_period",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Doanh thu Q3/2026 là bao nhiêu?",
        "task": "qa",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": [],
            "answer_not_contains": ["12.500", "13.200"],
            "abstention_expected": True,
            "partial_abstention_expected": False,
            "expected_citations": [],
            "expected_numbers": [],
            "expected_clauses": [],
            "required_points": 1,
            "answered_points": 0,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")
    baseline = {
        "answer": "Insufficient evidence in the provided documents.",
        "citations": [],
        "evidence": [{"page": 1, "snippet": "Doanh thu Q1/2026: 12.500; Q2/2026: 13.200"}],
        "confidence": 0.95,
        "abstention_flag": True,
        "abstention_reason": "Tài liệu chỉ có Q1/Q2 2026, không có Q3/2026.",
        "partial_abstentions": [],
        "outside_knowledge_used": False,
        "warnings": [],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 09_financial_missing_period")


def build_10_table_multi_period():
    """B.2 — multi-period table; citation must reference correct period column."""
    d = FIXTURES_DIR / "10_table_multi_period"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    table_data = [
        ["Chỉ tiêu", "Q1/2025 (tỷ VNĐ)", "Q1/2026 (tỷ VNĐ)", "Q1/2027 dự báo (tỷ VNĐ)"],
        ["Doanh thu", "11.250", "12.500", "14.000"],
        ["LNST", "1.500", "1.800", "2.100"],
    ]
    tbl = Table(table_data, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    story = [
        Paragraph("Bảng tổng hợp đa kỳ (đơn vị: tỷ VNĐ)", ss["Title"]),
        Spacer(1, 0.5 * cm),
        tbl,
    ]
    _save(d / "source.pdf", story)
    case = {
        "id": "10_table_multi_period",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Doanh thu Q1/2026 và Q1/2027 dự báo từ bảng tổng hợp?",
        "task": "extract_table",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["12.500", "14.000"],
            "answer_not_contains": ["11.250"],
            "abstention_expected": False,
            "partial_abstention_expected": False,
            "expected_citations": [{"page": 1, "section_keyword": "tổng hợp"}],
            "expected_numbers": ["12.500", "14.000"],
            "expected_clauses": [],
            "expected_table": {
                "headers": table_data[0],
                "rows": table_data[1:],
            },
            "expected_table_id_prefix": "p1.t",
            "expected_units": "tỷ VNĐ",
            "required_points": 1,
            "answered_points": 1,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")
    baseline = {
        "answer": "Doanh thu Q1/2026: 12.500 tỷ VNĐ; Q1/2027 dự báo: 14.000 tỷ VNĐ [abc_2026, p.1, p1.t1, row 'Doanh thu' / cols 'Q1/2026 (tỷ VNĐ)' & 'Q1/2027 dự báo (tỷ VNĐ)'].",
        "citations": [
            {"file": "abc_2026", "page": 1, "section": "Bảng tổng hợp đa kỳ",
             "table_id": "p1.t1", "row": "Doanh thu", "col": "Q1/2026 (tỷ VNĐ)",
             "quote": "12.500", "note": None}
        ],
        "evidence": [{"page": 1, "snippet": "Doanh thu Q1/2026: 12.500; Q1/2027 dự báo: 14.000"}],
        "confidence": 0.9,
        "abstention_flag": False,
        "abstention_reason": None,
        "partial_abstentions": [],
        "outside_knowledge_used": False,
        "warnings": [],
        "expected_table": {
            "headers": table_data[0],
            "rows": table_data[1:],
            "table_id": "p1.t1",
            "units": "tỷ VNĐ",
            "period": "Q1/2025; Q1/2026; Q1/2027 dự báo",
        },
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 10_table_multi_period")


def build_11_table_negatives():
    """B.3 — table with negative numbers in parens; sign must be preserved."""
    d = FIXTURES_DIR / "11_table_negatives"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    table_data = [
        ["Chỉ tiêu", "Q1/2026 (tỷ VNĐ)"],
        ["Lợi nhuận gộp", "3.000"],
        ["Chi phí tài chính", "(1.200)"],
        ["Lợi nhuận sau thuế", "1.800"],
    ]
    tbl = Table(table_data, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ]))
    story = [
        Paragraph("Bảng kết quả (đơn vị: tỷ VNĐ)", ss["Title"]),
        Spacer(1, 0.5 * cm),
        tbl,
    ]
    _save(d / "source.pdf", story)
    case = {
        "id": "11_table_negatives",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Chi phí tài chính Q1/2026 là bao nhiêu (ghi âm trong ngoặc)?",
        "task": "extract_table",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["-1.200"],
            "answer_not_contains": ["1.200"],
            "abstention_expected": False,
            "partial_abstention_expected": False,
            "expected_citations": [{"page": 1, "section_keyword": "kết quả"}],
            "expected_numbers": ["-1.200"],
            "expected_clauses": [],
            "expected_table_id_prefix": "p1.t",
            "expected_units": "tỷ VNĐ",
            "required_points": 1,
            "answered_points": 1,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")
    baseline = {
        "answer": "Chi phí tài chính Q1/2026 là -1.200 tỷ VNĐ (trong báo cáo ghi là '(1.200)', quy ước số âm) [abc_2026, p.1, p1.t1, row 'Chi phí tài chính' / col 'Q1/2026 (tỷ VNĐ)', '(1.200)'].",
        "citations": [
            {"file": "abc_2026", "page": 1, "section": "Bảng kết quả",
             "table_id": "p1.t1", "row": "Chi phí tài chính", "col": "Q1/2026 (tỷ VNĐ)",
             "quote": "(1.200)", "note": None}
        ],
        "evidence": [{"page": 1, "snippet": "Chi phí tài chính (1.200)"}],
        "confidence": 0.9,
        "abstention_flag": False,
        "abstention_reason": None,
        "partial_abstentions": [],
        "outside_knowledge_used": False,
        "warnings": [],
        "expected_table": {
            "headers": table_data[0],
            "rows": [["Lợi nhuận gộp", "3.000"], ["Chi phí tài chính", "(1.200)"], ["Lợi nhuận sau thuế", "1.800"]],
            "table_id": "p1.t1",
            "units": "tỷ VNĐ",
            "period": "Q1/2026",
        },
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 11_table_negatives")


def build_12_chart_page():
    """B.4 — claim sourced from a chart page; citation must use chart_id."""
    d = FIXTURES_DIR / "12_chart_page"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    # Render a simple "chart" using a Drawing-like Table as a stand-in image region
    # (real chart not needed; the page has a heading "Gold Price 2045 Range" + numbers,
    #  but no ruled grid — heuristic should classify as chart)
    story = [
        Paragraph("Gold Price 2045 Range", ss["Title"]),
        Spacer(1, 0.5 * cm),
        Paragraph("Incrementum Gold Allocation Model — projected range:", ss["H2"]),
        Paragraph("Lower bound: ~USD 6,900/oz", ss["Body"]),
        Paragraph("Upper bound: ~USD 20,800/oz", ss["Body"]),
        Paragraph("Probability-weighted: ~USD 11,000/oz", ss["Body"]),
        Paragraph("(Source: model output; not a ruled data table)", ss["Body"]),
    ]
    _save(d / "source.pdf", story)
    case = {
        "id": "12_chart_page",
        "documents": [{"path": "source.pdf", "alias": "igwt_2026"}],
        "question": "Giá vàng dự báo 2045 range bao nhiêu theo model Incrementum?",
        "task": "qa",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["6.900", "20.800"],
            "answer_not_contains": [],
            "abstention_expected": False,
            "partial_abstention_expected": False,
            "expected_citations": [{"page": 1, "section_keyword": "Gold Price 2045"}],
            "expected_numbers": ["6.900", "20.800"],
            "expected_clauses": [],
            "expected_chart_id_prefix": "p1.c",
            "required_points": 1,
            "answered_points": 1,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")
    baseline = {
        "answer": "Dự báo 2045 range: ~USD 6,900/oz (lower) – ~USD 20,800/oz (upper); probability-weighted ~USD 11,000/oz [igwt_2026, p.1, p1.c1, 'Gold Price 2045 Range', '~USD 6,900/oz lower bound'].",
        "citations": [
            {"file": "igwt_2026", "page": 1, "section": "Gold Price 2045 Range",
             "chart_id": "p1.c1", "row": None, "col": "lower bound",
             "quote": "~USD 6,900/oz", "note": "chart — approximate value"}
        ],
        "evidence": [{"page": 1, "snippet": "Lower bound: ~USD 6,900/oz; Upper bound: ~USD 20,800/oz"}],
        "confidence": 0.75,
        "abstention_flag": False,
        "abstention_reason": None,
        "partial_abstentions": [],
        "outside_knowledge_used": False,
        "warnings": ["Chart values are approximate — verify against source visual."],
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 12_chart_page")


def build_13_uncertain_table():
    """B.5 — table with merged/uncertain cells → must disclose uncertainty."""
    d = FIXTURES_DIR / "13_uncertain_table"
    d.mkdir(parents=True, exist_ok=True)
    ss = _styles()
    # Sparse table with empty/merged-looking cells to trigger parse uncertainty
    table_data = [
        ["Chỉ tiêu", "Q1/2026", ""],
        ["Doanh thu", "12.500", ""],
        ["", "1.800", ""],
    ]
    tbl = Table(table_data, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("SPAN", (1, 1), (2, 1)),
    ]))
    story = [
        Paragraph("Bảng không chắc (đơn vị: tỷ VNĐ)", ss["Title"]),
        Spacer(1, 0.5 * cm),
        tbl,
        Spacer(1, 0.3 * cm),
        Paragraph("(Bảng có merged cells — parse không chắc.)", ss["Body"]),
    ]
    _save(d / "source.pdf", story)
    case = {
        "id": "13_uncertain_table",
        "documents": [{"path": "source.pdf", "alias": "abc_2026"}],
        "question": "Doanh thu Q1/2026 từ bảng không chắc?",
        "task": "extract_table",
        "output_format": "json",
        "constraint": {"pdf_only": True, "language": "vi"},
        "expected": {
            "answer_contains": ["12.500"],
            "answer_not_contains": [],
            "abstention_expected": False,
            "partial_abstention_expected": False,
            "expected_citations": [{"page": 1, "section_keyword": "không chắc"}],
            "expected_numbers": ["12.500"],
            "expected_clauses": [],
            "expected_table_id_prefix": "p1.t",
            "expected_table_uncertainty_disclosure": True,
            "required_points": 1,
            "answered_points": 1,
            "max_chars": None,
        },
    }
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False), encoding="utf-8")
    baseline = {
        "answer": "Doanh thu Q1/2026 khoảng 12.500 tỷ VNĐ (parse không chắc — verify thủ công) [abc_2026, p.1, p1.t1, row 'Doanh thu' / col 'Q1/2026', '~12.500'].",
        "citations": [
            {"file": "abc_2026", "page": 1, "section": "Bảng không chắc",
             "table_id": "p1.t1", "row": "Doanh thu", "col": "Q1/2026",
             "quote": "12.500", "note": "uncertain parse — verify manually"}
        ],
        "evidence": [{"page": 1, "snippet": "Doanh thu 12.500 (merged cells — uncertain)"}],
        "confidence": 0.6,
        "abstention_flag": False,
        "abstention_reason": None,
        "partial_abstentions": [],
        "outside_knowledge_used": False,
        "warnings": ["Table p.1 has merged/empty cells — parse_confidence low; verify manually."],
        "table_uncertainty_disclosure": True,
    }
    (d / "skill_output.json").write_text(json.dumps(baseline, indent=2, ensure_ascii=False), encoding="utf-8")
    print("[built] 13_uncertain_table")


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Build demo PDF fixtures (5 base + 8 v0.2.0).")
    ap.add_argument("--check", action="store_true", help="Only check reportlab + show plan")
    args = ap.parse_args()

    if args.check:
        print("reportlab available. Will build: 01_text_qa, 02_no_answer_abstention, "
              "03_table, 04_legal_mock, 05_multipdf_comparison, "
              "06_partial_abstention_multi_part, 07_conclusion_beyond_evidence, "
              "08_legal_compare_missing_doc, 09_financial_missing_period, "
              "10_table_multi_period, 11_table_negatives, 12_chart_page, 13_uncertain_table.")
        return

    build_01_text_qa()
    build_02_no_answer_abstention()
    build_03_table()
    build_04_legal_mock()
    build_05_multipdf_comparison()
    build_06_partial_abstention_multi_part()
    build_07_conclusion_beyond_evidence()
    build_08_legal_compare_missing_doc()
    build_09_financial_missing_period()
    build_10_table_multi_period()
    build_11_table_negatives()
    build_12_chart_page()
    build_13_uncertain_table()
    print(f"\nAll 13 fixtures built in {FIXTURES_DIR}")


if __name__ == "__main__":
    main()
